server:
    error:
        include-message: always
    port: 8080
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgres00
        url: jdbc:postgresql://localhost:5432/restaurantData
        username: postgres
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    jwt:
        secret_key: RESTAURANT_00_SECRET_CODE
    main:
        allow-circular-references: true
